spring:
  application:
    name: edges_test
  datasource:
    url: jdbc:postgresql://localhost:5432/edge_db
    driverClassName: org.postgresql.Driver
    username: edge_user
    password: "S3cret"
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  jooq:
    sql-dialect: postgres
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=10000

server:
  port: 9080

info:
  application:
    name: ${spring.application.name}
    description: edges test app
    team: My Team
    company: MyCompany

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      path-mapping:
        prometheus: "prometheus"
  metrics:
    tags:
      application: edges_test
  info:
    build:
      enabled: true
    env:
      enabled: true
    git:
      enabled: true
      mode: full
    java:
      enabled: true
  endpoint:
    health:
      show-details: never

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    org:
      springframework:
        security: DEBUG
        transaction: TRACE
        jdbc:
          datasource:
            DataSourceTransactionManager: TRACE
      flywaydb: DEBUG
      jooq:
        tools:
          LoggerListener: DEBUG
